var $table = $("table");
var $header = $("header");
var $formElement = $("form");
var $p = $("p");
var $formTitle = $(".form-title");
var $studentName = $(".name");
var $courseName = $(".course");
var $studentGrade = $(".grade");
var $submitButton = $("button.btn-success");
console.log($submitButton);
var gradeTable = new GradeTable($table, $p);
var pageHeader = new PageHeader($header);
var gradeForm = new GradeForm($formElement, $studentName, $courseName, $studentGrade, $formTitle, $submitButton);
var app = new App(gradeTable, pageHeader, gradeForm);
app.start();
